#!/usr/bin/python

import xbot
from ConfigParser import ConfigParser

if __name__ == "__main__":
	config = ConfigParser()
	if config.read('/etc/xbot/xbot.conf'):
		bot = xbot.Initialise([server.strip().split(":") for server in config.get(config.sections()[1], 'servers').split(",")], config)
		bot.run()
	else:
		print "Error: Cannot read xBot configuration file."
		print "Please see INSTALL for help."